version: '3.8'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    # ports:
    #   - 27017:27017
    env_file:
      - ../.env

  app:
    build: ../
    restart: always
    volumes:
      - ..:/salary_aggregation
    depends_on:
      - mongodb
    env_file:
      - ../.env
    ports:
      - '443:443'

volumes:
  mongodb-data:
